<?php

/**
 * @file
 * Contains roosevelt_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\file\Entity\File;

/**
 * Implements hook_help().
 */
function roosevelt_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the roosevelt_custom module.
    case 'help.page.roosevelt_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Roosevelt customizations of views, settings, etc.') . '</p>';
      return $output;

    default:
  }
}

/**
   * Implements hook_module_implements_alter().
   */
function roosevelt_custom_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    // Move our hook_entity_presave() implementation to the end of the list.
    case 'entity_presave':
      $group = $implementations['roosevelt_custom'];
      unset($implementations['roosevelt_custom']);
      $implementations['roosevelt_custom'] = $group;
      break;
  }
}
/**
 * hook_form_BASE_FORM_ID_alter() for the node_form.
 */
function roosevelt_custom_form_user_form_alter(&$form, FormStateInterface $form_state) {
  $form['field_full_name']['#type'] = 'hidden';
}

/**
 * Implements hook_entity_presave().
 */
function roosevelt_custom_entity_presave(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'user':
      $title_data = [
        'first' => $entity->field_first_name->value,
        'last' => $entity->field_last_name->value,
      ];
  
      // Remove empty values and convert to string
      $title_data = array_filter($title_data);
      $title = implode(' ', $title_data);
  
      $entity->set('field_full_name', $title);
      
      break;
  }
}
