<?php

/**
 * @file
 * Contains roosevelt_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\file\Entity\File;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function roosevelt_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the roosevelt_custom module.
    case 'help.page.roosevelt_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Roosevelt customizations of views, settings, etc.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function roosevelt_custom_theme($existing, $type, $theme, $path) {
  return [
    'search_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
   * Implements hook_module_implements_alter().
   */
function roosevelt_custom_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    // Move our hook_entity_presave() implementation to the end of the list.
    case 'entity_presave':
      $group = $implementations['roosevelt_custom'];
      unset($implementations['roosevelt_custom']);
      $implementations['roosevelt_custom'] = $group;
      break;
  }
}

/**
 * hook_form_BASE_FORM_ID_alter() for the node_form.
 */
function roosevelt_custom_form_user_form_alter(&$form, FormStateInterface $form_state) {
  // Hide full name field because it is created dynamically
  $form['field_full_name']['#type'] = 'hidden';

  // Validate the Net ID field is unique
  $form['#validate'][] = 'validateIsUnique';

  // Format the telephone fields to be pretty
  $form['field_primary_phone']['widget'][0]['value']['#attributes'] = ["pattern" => "[0-9]{3}-[0-9]{3}-[0-9]{4}"];
  $form['field_primary_phone']['widget'][0]['value']['#placeholder'] = 'eg. 999-999-9999';
  $form['field_secondary_phone']['widget'][0]['value']['#attributes'] = ["pattern" => "[0-9]{3}-[0-9]{3}-[0-9]{4}"];
  $form['field_secondary_phone']['widget'][0]['value']['#placeholder'] = 'eg. 999-999-9999';

  // Per spec, hide the mail field from user form
  $form['account']['mail']['#access'] = false;
}

/**
 * hook_form_BASE_FORM_ID_alter() for the node_form.
 */
function roosevelt_custom_form_block_content_outcome_form_alter(&$form, FormStateInterface $form_state) {
  $form['info']['widget'][0]['value']['#title'] = t('Label');
}

/**
 * hook_form_BASE_FORM_ID_alter() for the node_form.
 */
function roosevelt_custom_form_block_content_differentiators_form_alter(&$form, FormStateInterface $form_state) {
  $form['info']['widget'][0]['value']['#title'] = t('Differentiator Name');
}

/**
 * Implements hook_entity_presave().
 */
function roosevelt_custom_entity_presave(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'user':
      // Build the full name field
      $title_data = [
        'first' => $entity->field_first_name->value,
        'last' => $entity->field_last_name->value,
      ];

      // Remove empty values and convert to string
      $title_data = array_filter($title_data);
      $title = implode(' ', $title_data);

      $entity->set('field_full_name', $title);
      break;
  }
}

/**
 * Adds custom validation to the user edit/add form
 */
function validateIsUnique(array &$form, FormStateInterface $form_state) {
  if (!empty($form_state->getValue('field_netid'))) {
    $unique = $form_state->getValue('field_netid')[0]['value'];

    if (isset($unique)) {
      // Get any user with the same netid value
      $query = \Drupal::entityQuery('user')
        ->condition('field_netid', $unique);
      $uids = $query->execute();

      // If we are editing an existing user, remove it from the results
      if($uid = $form_state->getformObject()->getEntity()->id()) {
        unset($uids[$uid]);
      }

      // If there is a user with the same netid, return and error message
      if(count($uids) > 0) {
        $form_state->setErrorByName('field_netid', 'The Net ID field must be unique for each user.');
      }
    }
  }
}

/**
 * Implements hook_entity_view_mode_alter().
 */
function roosevelt_custom_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context) {
  // Determine proper display mode for remote_video in textsection paragraph.
  if ($entity->bundle() == 'remote_video') {
    $referencing_field = $entity->_referringItem->getParent();
    $parent_entity = $referencing_field->getParent();
    $paragraph_entity = $parent_entity->getEntity();
    if ($paragraph_entity->bundle() == 'textsection') {
      $view_mode = 'default';
      if ($parent_entity->get('field_mediaboxvariant')->value == 1) {
        $view_mode = 'modal';
      }
      elseif ($parent_entity->get('field_mediaboxvariant')->value == 0) {
        $view_mode = 'media_box';
      }
    }
  }
}

/**
 * hook_form_BASE_FORM_ID_alter() for the node_form.
 */
function roosevelt_custom_form_node_program_edit_form_alter(&$form, FormStateInterface $form_state) {
  _node_form_alter($form, $form_state);
}

/**
 * hook_form_BASE_FORM_ID_alter() for the node_form.
 */
function roosevelt_custom_form_node_program_form_alter(&$form, FormStateInterface $form_state) {
  _node_form_alter($form, $form_state);
}

/**
 * hook_form_BASE_FORM_ID_alter() for the node_form.
 */
function _node_form_alter(&$form, FormStateInterface $form_state) {
  $testimonials = views_embed_view('program_testimonials', 'list');

  $form['testimonials'] = [
    '#title' => t('Testimonials'),
    '#group' => 'advanced',
    '#type' => 'details',
    '#access' => TRUE,
    '#open' => FALSE,
    '#tree' => TRUE,
    '#weight' => 99,
  ];
  $form['testimonials']['list'] = [
    '#markup' => '<p>The ability to add <em>Testimonials</em> will be available after the node has been created.</p>',
    '#weight' => -1,
  ];

  if ($form['#form_id'] === 'node_program_edit_form') {
    $form['testimonials']['#open'] = TRUE;
    $destination = \Drupal::destination()->getAsArray();
    $block_add_url = '/block/add/testimonial';
    $block_add_url_options = [
      'attributes' => [
        'class' => ['button'],
      ],
      'query' => [
        $destination,
      ],
    ];
    $link_markup = Link::fromTextAndUrl(t('Add Testimonial'),
        Url::fromUserInput($block_add_url, $block_add_url_options))->toString();

    $form['testimonials']['add_testimonial'] = [
      '#type' => 'markup',
      '#markup' => $link_markup,
      '#weight' => 0,
      '#cache' => [
        'contexts' => ['url.query_args'],
      ],
      '#attributes' => [
        'class' => ['button'],
      ],
    ];

    $form['testimonials']['list'] = $testimonials;
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert() for 'paragraph'.
 * Helper for Feeds.
 */
function roosevelt_custom_paragraph_insert(EntityInterface $paragraph) {
  $type = $paragraph->type->target_id;
  if ($type == 'user_education' || $type == 'user_expertise' || $type == 'user_social_media') {
    $parent_type = 'user';
    $parent_field_name = 'field_'.$type;
    ///Get user id from NetID
    $parent_id = $paragraph->parent_id->value;
    $user = user_load_by_name($parent_id);
    if($user){
      // Check if entity already has a reference to this paragraph.
      foreach ($user->{$parent_field_name} as $item) {
        if ($item->target_id == $paragraph->id()) {
          // Paragraph found. Abort.
          return;
        }
      }
      $user->{$parent_field_name}[] = $paragraph;
      $user->save();
    }else{
      //Orphan Record --- how to avoid save it?
    }
  }
}
