#!/usr/bin/env bash

#: exec_target = cli

## Run Gulp Commands on the theme
##
## Usage: fin patterns [arguments]
##

# Abort if anything fails
set -e

cd ${PROJECT_ROOT}/web/libraries/patterns

gulp "$@"
