#!/usr/bin/env bash

#: exec_target = cli

## Run Gulp Commands on the theme
##
## Usage: fin theme [arguments]
##

# Abort if anything fails
set -e

cd ${PROJECT_ROOT}/web/themes/custom/roosevelt

gulp "$@"
