#!/usr/bin/env bash

#: exec_target = cli

# Abort if anything fails
set -e

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
THEME_PATH="${PROJECT_ROOT}/${DOCROOT}/themes/custom/roosevelt"
PATTERNS_PATH="${PROJECT_ROOT}/${DOCROOT}/libraries/patterns"

echo "Checking theme ..."
if [ ! -d "${THEME_PATH}/node_modules" ]; then
  cd ${THEME_PATH}
  echo "Running npm install ..."
  npm install
fi

echo "Checking pattern lab ..."
if [ ! -d "${PATTERNS_PATH}/node_modules" ]; then
  cd ${PATTERNS_PATH}
  echo "Running npm install ..."
  npm install
fi

if [ ! -d "${PATTERNS_PATH}/patternlab/vendor" ]; then
  cd ${PATTERNS_PATH}/patternlab
  echo "Running composer install ..."
  composer install
fi
